export const currencyByRupee: Currency[] = [
    {
        name: 'USD',
        value: 0.014,
        flag: '🇺🇸',
        symbol: '$',
    },
    {
        name: 'EUR',
        value: 0.012,
        flag: '🇪🇺',
        symbol: '€',
    },
    {
        name: 'JPY',
        value: 1.53,
        flag: '🇯🇵',
        symbol: '¥',
    },
    {
        name: 'GBP',
        value: 0.011,
        flag: '🇬🇧',
        symbol: '£',
    },
    {
        name: 'AUD',
        value: 0.019,
        flag: '🇦🇺',
        symbol: 'A$',
    },
    {
        name: 'Dirham',
        value: 0.051,
        flag: '🇦🇪',
        symbol: 'د.إ',
    },
    {
        name: 'Chinese Yuan',
        value: 0.09,
        flag: '🇨🇳',
        symbol: '¥',
    },
    {
        name: 'SGD',
        value: 0.019,
        flag: '🇸🇬',
        symbol: 'S$',
    },
    {
        name: 'Rubel',
        value: 1.02,
        flag: '🇷🇺',
        symbol: '₽',
    },
    {
        name: 'CAD',
        value: 0.018,
        flag: '🇨🇦',
        symbol: 'C$',
    },
    {
        name: 'CHF',
        value: 0.013,
        flag: '🇨🇭',
        symbol: 'Fr',
    },
    {
        name: 'BRL',
        value: 0.071,
        flag: '🇧🇷',
        symbol: 'R$',
    },
    {
        name: 'KRW',
        value: 16.26,
        flag: '🇰🇷',
        symbol: '₩',
    },
    {
        name: 'TRY',
        value: 0.12,
        flag: '🇹🇷',
        symbol: '₺',
    },
    {
        name: 'ZAR',
        value: 0.21,
        flag: '🇿🇦',
        symbol: 'R',
    },
    {
        name: 'MXN',
        value: 0.28,
        flag: '🇲🇽',
        symbol: 'Mex$',
    },
    {
        name: 'IDR',
        value: 200.0,
        flag: '🇮🇩',
        symbol: 'Rp',
    },
    {
        name: 'SAR',
        value: 0.052,
        flag: '🇸🇦',
        symbol: '﷼',
    },
    {
        name: 'THB',
        value: 0.44,
        flag: '🇹🇭',
        symbol: '฿',
    },
    {
        name: 'KWD',
        value: 0.0042,
        flag: '🇰🇼',
        symbol: 'د.ك',
    },
    {
        name: 'EGP',
        value: 0.22,
        flag: '🇪🇬',
        symbol: 'E£',
    },
];
